const DICTIONARY = {
  en: {
    MENU_TITLE: "MENU",
    MENU_PLAY_GAME: "1. Play Game",
    MENU_PVC_GAME: "2. PvC (Player vs Computer)",
    MENU_SETTINGS: "3. Settings",
    MENU_EXIT: "4. Exit Game",
    INVALID_MOVE: "Invalid move. Please try again.",
    TURN_PROMPT: "Player {PLAYER} it is your turn",
    PLACE_MARK: "Place your mark at: ",
    PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
    CONFIRM: "y",
    DRAW: "It's a draw!!",
    WINNER: "Winner is player ",
    GAME_OVER: "GAME OVER",
    PLAYER_DESCRIPTION_ONE: "one",
    PLAYER_DESCRIPTION_TWO: "two",
    SELECT_LANGUAGE: "Select language",
    LANG_EN: "English",
    LANG_NO: "Norwegian",
    AI_TURN_PROMPT: "AI's turn...",
  },
  no: {
    MENU_TITLE: "MENY",
    MENU_PLAY_GAME: "1. Spill spill",
    MENU_PVC_GAME: "2. Spiller mot datamaskin (PvC)",
    MENU_SETTINGS: "3. Innstillinger",
    MENU_EXIT: "4. Avslutt spill",
    INVALID_MOVE: "Ugyldig trekk. Prøv på nytt.",
    TURN_PROMPT: "Spiller {PLAYER}, det er din tur",
    PLACE_MARK: "Plasser merket ditt på: ",
    PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
    CONFIRM: "j",
    DRAW: "Det er uavgjort!!",
    WINNER: "Vinneren er spiller ",
    GAME_OVER: "SPILLET ER OVER",
    PLAYER_DESCRIPTION_ONE: "en",
    PLAYER_DESCRIPTION_TWO: "to",
    SELECT_LANGUAGE: "Velg språk",
    LANG_EN: "Engelsk",
    LANG_NO: "Norsk",
    AI_TURN_PROMPT: "Datamaskinens tur...",
  },
};

export default DICTIONARY;
